name: Deploy CDK Stack

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

env:
  AWS_REGION: ap-south-1
  CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
  CDK_DEFAULT_REGION: ap-south-1
permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.CDK_DEFAULT_ACCOUNT }}:role/Mirror-Management-github-role
          role-session-name: github-actions-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Install CDK
        run: |
          npm install -g aws-cdk

      - name: Install Python dependencies
        working-directory: ./infra
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-infra.txt

      - name: Bootstrap CDK (if needed)
        working-directory: ./infra
        run: |
          cdk bootstrap aws://${{ env.CDK_DEFAULT_ACCOUNT }}/${{ env.AWS_REGION }} || true

      - name: Synthesize CDK
        working-directory: ./infra
        run: |
          cdk synth

      - name: Deploy CDK Stack
        working-directory: ./infra
        run: |
          cdk deploy --require-approval never
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          DEFAULT_AWS_REGION: ${{ env.AWS_REGION }}

      - name: Get API Gateway URL
        working-directory: ./infra
        run: |
          API_URL=$(aws apigateway get-rest-apis --query 'items[?name==`Mirror Management API`].id' --output text)
          echo "API Gateway URL: https://$API_URL.execute-api.${{ env.AWS_REGION }}.amazonaws.com/prod/"
          echo "API_URL=https://$API_URL.execute-api.${{ env.AWS_REGION }}.amazonaws.com/prod/" >> $GITHUB_ENV
